
import React, { useState } from 'react';
import { JsonViewer } from './components/JsonViewer';

// Note: The user provided two identical JSON objects. We will visualize one.
const protocolData = {
  "Protocol_Name": "Meta-Cognitive Context Loom",
  "The_Blend_Emergent_Structure": "By synthesizing epistemic understanding with context mechanics, the protocol transforms tool-definition overhead (Input Space 2) into a scaffold for causal reasoning (Input Space 1). The 16% context cost becomes a forced articulation of explanatory relationships *before* execution, converting mechanical constraint into epistemic opportunity. This creates a self-reinforcing loop: tool scaffolding generates understanding, which optimizes future context allocation, making the system antifragile to context constraints.",
  "Mechanism_1_Surrogate_Reasoning": {
    "Core_Process": "Tool definitions are repurposed as executable epistemic blueprints during context initialization. Instead of passive metadata, they trigger automatic generation of a 'Causal Validation Matrix' (CVM).",
    "Implementation": "For each enabled tool (e.g., Contact 7, Playwright), the agent extracts its functional purpose and maps it to: (a) required causal dependencies, (b) failure conditions, and (c) cross-tool interaction principles. This matrix consumes the 'overhead' tokens but pre-builds a task-specific understanding framework.",
    "Epistemic_Benefit": "The CVM acts as surrogate reasoning infrastructure, allowing the agent to simulate outcomes and validate task coherence *before* token-intensive execution. This reduces runtime context usage by 22% in benchmarks by shifting understanding to the pre-execution phase."
  },
  "Mechanism_2_Antifragility_Injection": {
    "Trigger": "When >3 consecutive tool invocations fail validation against the CVM",
    "Refinement_Cycle": "Automatically injects a Contradictory Hypothetical: 'Assume all tool definitions are inverted (e.g., Contact 7 *creates* data silos). Rebuild the CVM under this constraint.'",
    "Failure_Utility_Mechanism": "The contradiction forces re-evaluation of hidden assumptions. The agent quantifies 'coherence debt' (divergence between original and inverted CVMs) to surgically refine context allocation, converting failures into understanding upgrades."
  },
  "Testing_Hypothesis": "ECO reduces context consumption variance by ≥40% in multi-step workflows while increasing cross-domain task transfer success by ≥30%, measured by deterministic outcome alignment (e.g., 'user goal achieved with minimal corrections') rather than output text similarity.",
  "Epistemic_Flow_Metric": [
    "Causal Density Index: Ratio of context tokens explicitly mapping cause-effect relationships versus descriptive facts during task decomposition",
    "Counterfactual Adaptation Speed: Time-steps required to successfully execute a modified task after antifragility injection, normalized against baseline re-planning overhead"
  ]
};

const App: React.FC = () => {
  return (
    <div className="min-h-screen bg-slate-900 text-slate-200 flex flex-col items-center p-4 sm:p-6 md:p-8">
      <div className="w-full max-w-4xl">
        <header className="mb-8 text-center">
          <h1 className="text-3xl sm:text-4xl font-bold text-cyan-400 tracking-tight">
            Meta-Cognitive Context Loom
          </h1>
          <p className="mt-2 text-slate-400 text-lg">
            An interactive protocol visualizer.
          </p>
        </header>
        <main>
          <JsonViewer data={protocolData} />
        </main>
        <footer className="text-center mt-12 text-slate-500 text-sm">
          <p>Generated by a world-class senior frontend React engineer.</p>
        </footer>
      </div>
    </div>
  );
};

export default App;
